// Generated by https://quicktype.io

export interface UserDetails {
    uid: string;
    accessToken: string;
    email: string;
    emailVerified: boolean;
    createdAt: Date;
}

export const makeDefaultUserDetails = (): UserDetails => ({
    uid: "6O0d1iiAl4Mm7wN3Cc5b6rvh27h2",
    accessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY1NWU0ZDkxOGE0ODY0YWQxMzUxMDViYmRjMDEwYWY5Njc5YzM0MTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVkLWVxdWlub3gtMzA0NzE3IiwiYXVkIjoicmVkLWVxdWlub3gtMzA0NzE3IiwiYXV0aF90aW1lIjoxNjczNTE3NjYzLCJ1c2VyX2lkIjoiNk8wZDFpaUFsNE1tN3dOM0NjNWI2cnZoMjdoMiIsInN1YiI6IjZPMGQxaWlBbDRNbTd3TjNDYzViNnJ2aDI3aDIiLCJpYXQiOjE2NzM1MTc2NjMsImV4cCI6MTY3MzUyMTI2MywiZW1haWwiOiJ0ZXN0QHRlc3QudGVzdCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QudGVzdCJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.udM9pibhMaM1Oy8KuSbIclDcOXFDgmQRJmdM5Hf6PclOFPgTkYqnWNRC1h_hOGY7GjEekqr2LZxYKbvyxXndvyX2zcqBGirO20RqT_bdzKs15KzucIC9nO_-SqOXJ9zdO2Gxagw28Ezdp0-Qv1gVEI8kdcNMNi4LdcwUr9gVnFJDh2xec6L2OmmXAaXnO-ySdJx8HVviNCdRlDLLHI8S5lz_UmsHzWeokKR57_tYXa1nu4UI0xWbe1Q1oj8B-I5E7Qne_Kg6ddIBrb1YQ67TAh7LOXYMCD3rqCGYbHuQoltkv-wbfOeFNMJyqjlMiLYZk_MZUi5T7bEHppddSWV8wg",
    email: "test@test.test",
    emailVerified: true,
    createdAt: new Date("2018-12-04")
})